Repository NullTraining/reviewz, pull requests merged in 2018-03, with the labels that each got.

#36 #18 - Organization modeling
  spec/Organization/Controller/OrganizationControllerSpec.php
  spec/Organization/Entity/OrganizationEntitySpec.php
  src/Organization/Controller/OrganizationController.php
  src/Organization/Entity/OrganizationEntity.php
Labels: ready to merge

#40 Vagrant setup
  .gitignore
  README.md
  Vagrantfile
  vagrant/config/.gitignore
  vagrant/config/vagrant-local.example.yml
  vagrant/nginx/app.conf
  vagrant/nginx/log/.gitignore
  vagrant/provision/always-as-root.sh
  vagrant/provision/once-as-root.sh
  vagrant/provision/once-as-vagrant.sh
Labels: ready to merge

#49 #29 Add Feedback entity
  spec/Talk/Entity/FeedbackEntitySpec.php
  src/Talk/Entity/FeedbackEntity.php
Labels: feature, ready to merge

#45 Issue 21 event creating
  spec/Event/Controller/EventControllerSpec.php
  spec/Event/Entity/EventEntitySpec.php
  src/Event/Controller/EventController.php
  src/Event/Entity/EventEntity.php
  src/Organization/Entity/OrganizationEntity.php
Labels: fixed, ready to merge

#56 Replace Zend\EventManager\Exception\DomainException with DomainException
  src/Event/Controller/EventController.php
Labels: ready for review

#52 Issue 21 event location
  spec/Event/Controller/EventControllerSpec.php
  spec/Event/Entity/EventEntitySpec.php
  src/Event/Controller/EventController.php
  src/Event/Entity/EventEntity.php
Labels: ready to merge

#57 Organizer can add a talk
  spec/Talk/Controller/TalkControllerSpec.php
  src/Talk/Controller/TalkController.php
Labels: ready to merge
