Repository NullTraining/reviewz, pull requests merged in 2018-06, with the labels that each got.

#171 Issue #170 - Rename entity examples in Behat scenarios
  features/claim-talk.feature
  features/create-organization.feature
  features/join-organization.feature
  features/managing-new-organizations.feature
  features/organizer-can-create-event.feature
  features/rsvp-to-event.feature
  src/Event/Behat/EventDomainContext.php
  src/Organization/Behat/OrganizationFixturesContext.php
  src/Talk/Behat/TalkApplicationContext.php
  src/User/Behat/UserApplicationContext.php
Labels: ready to merge

#173 [Exploratory] Force ansi output through Phing commands
  build.xml
Labels: exploratory, feature, ready for review

#139 Organizer manages user attendance
  behat.yml.dist
  features/organizer-marks-user-attendance.feature
  src/Event/Behat/EventDomainContext.php
Labels: ready for review

#178 Use regex to match all MockInterface errors that phpstan finds
  phpstan.neon
Labels: ready to merge

#179 Remove "Local organization" from fixtures
  src/Event/Behat/EventDomainContext.php
  src/Organization/Behat/OrganizationFixturesContext.php
Labels: ready for review
