Repository NullTraining/reviewz, pull requests merged in 2018-05, with the labels that each got.

#99 BUGFIX: Users being created in EventDomainContext are missing UserId :(
  src/Event/Behat/EventDomainContext.php
Labels: bug, high priority, ready to merge

#77 Feature #21 [Behat] Organizers Can Create New Events
  features/organizer-can-create-event.feature
  src/Event/Behat/EventDomainContext.php
Labels: ready to merge

#117 Add UserFixturesContext
  behat.yml.dist
  src/Event/Behat/EventDomainContext.php
  src/Talk/Behat/TalkDomainContext.php
  src/User/Behat/UserApplicationContext.php
  src/User/Behat/UserDomainContext.php
  src/User/Behat/UserFixturesContext.php
Labels: ready to merge

#119 BUGFIX: By mistake, CommandBus was extending wrong class :(
  src/App/CommandBus.php
Labels: ready to merge

#122 BUGFIX: Missing organization argument
  phpstan.neon
  src/Talk/Behat/TalkApplicationContext.php
Labels: ready to merge

#127 Instead of mocking current user, use transformation provider
  behat.yml.dist
  src/Event/Behat/EventDomainContext.php
  src/Organization/Behat/OrganizationDomainContext.php
  src/Talk/Behat/TalkDomainContext.php
Labels: ready to merge

#125 Save claimed talk using TalkRepository
  spec/Talk/Handler/ClaimTalkHandlerSpec.php
  src/Talk/Handler/ClaimTalkHandler.php
Labels: fixed, ready to merge
